FROM mcr.microsoft.com/playwright:v1.52.0-noble

WORKDIR /app/frontend
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx playwright install chromium

CMD ["npx", "playwright", "test", "--config=playwright.config.ts"]
